#!/usr/bin/env python3
"""Visualize extracted grasp poses from a summary file (JSON or pickle)."""

import argparse
import json
import pickle
import sys
from pathlib import Path
from typing import Dict, Optional

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from reset.extract_from_demo.extract_grasp import _render_from_summary


def load_summary(summary_path: Path) -> Dict:
    """Load summary from JSON or pickle file."""
    if not summary_path.is_file():
        raise FileNotFoundError(f"Summary file not found: {summary_path}")
    
    if summary_path.suffix == ".pkl":
        # Load from pickle
        with open(summary_path, "rb") as f:
            summary = pickle.load(f)
    elif summary_path.suffix == ".json":
        # Load from JSON
        with open(summary_path, "r", encoding="utf-8") as f:
            summary = json.load(f)
    else:
        raise ValueError(f"Unsupported file format: {summary_path.suffix}. Expected .pkl or .json")
    
    return summary


def print_summary_info(summary: Dict):
    """Print information about the loaded summary."""
    print("\n" + "="*60)
    print("Summary Information")
    print("="*60)
    
    for furniture_name, parts_data in summary.items():
        print(f"\nFurniture: {furniture_name}")
        print(f"  Parts: {len(parts_data)}")
        
        for part_name, stats in parts_data.items():
            samples = stats.get("samples", 0)
            mean_rel_pos = stats.get("mean_relative_position", [0, 0, 0])
            mean_rel_dist = stats.get("mean_relative_distance", 0.0)
            print(f"    - {part_name}: {samples} samples, mean distance: {mean_rel_dist:.4f}m")
            print(f"      mean rel pos: [{mean_rel_pos[0]:.4f}, {mean_rel_pos[1]:.4f}, {mean_rel_pos[2]:.4f}]")


def main():
    parser = argparse.ArgumentParser(
        description="Visualize extracted grasp poses from a summary file (.pkl or .json)"
    )
    parser.add_argument(
        "--summary",
        type=Path,
        required=True,
        help="Path to the summary file (.pkl or .json) generated by extract_grasp.py"
    )
    parser.add_argument(
        "--furniture",
        type=str,
        default=None,
        help="Filter by furniture name (default: visualize all furniture in summary)"
    )
    parser.add_argument(
        "--part",
        type=str,
        default=None,
        help="Filter by part name (default: visualize all parts)"
    )
    parser.add_argument(
        "--samples",
        type=int,
        default=5,
        help="Number of samples to visualize per part (currently not used, kept for compatibility)"
    )
    parser.add_argument(
        "--spread-mult",
        type=float,
        default=1.0,
        help="Multiplier on positional std when sampling part poses (currently not used, kept for compatibility)"
    )
    parser.add_argument(
        "--no-info",
        action="store_true",
        help="Don't print summary information before visualization"
    )
    parser.add_argument(
        "--use-viser",
        action="store_true",
        help="Use viser for visualization instead of Open3D"
    )
    
    args = parser.parse_args()
    
    # Load summary
    summary_path = args.summary.expanduser().resolve()
    print(f"Loading summary from: {summary_path}")
    
    try:
        summary = load_summary(summary_path)
    except Exception as e:
        print(f"ERROR: Failed to load summary file: {e}")
        sys.exit(1)
    
    # Print summary information
    if not args.no_info:
        print_summary_info(summary)
    
    # Validate filters
    if args.furniture is not None:
        if args.furniture not in summary:
            print(f"\nERROR: Furniture '{args.furniture}' not found in summary")
            print(f"Available furniture: {list(summary.keys())}")
            sys.exit(1)
        
        if args.part is not None:
            parts_data = summary[args.furniture]
            if args.part not in parts_data:
                print(f"\nERROR: Part '{args.part}' not found in furniture '{args.furniture}'")
                print(f"Available parts: {list(parts_data.keys())}")
                sys.exit(1)
    
    # Visualize
    print(f"\n{'='*60}")
    print("Visualizing grasps...")
    print(f"{'='*60}")
    print("Controls:")
    print("  - Mouse: Rotate (left drag), Pan (right drag), Zoom (scroll)")
    print("  - Press 'Q' or close window to exit")
    print()
    
    try:
        _render_from_summary(
            summary=summary,
            furniture_filter=args.furniture,
            part_filter=args.part,
            samples=args.samples,
            spread_mult=args.spread_mult,
            use_viser=args.use_viser,
        )
    except Exception as e:
        print(f"ERROR during visualization: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    
    print("\nVisualization complete!")


if __name__ == "__main__":
    main()

